// ─────────────────────────────────────────────────────────────────────────────
// cffReader.js
//
// Read the latest CFF (Cashflow Forecast) xlsx for a project and parse out:
//   • contract_sum       — total contract value the CFF covers
//   • months[]           — column labels (e.g. ["Apr 26", "May 26", ...])
//   • monthly[]          — MONTHLY GROSS VALUATION row, one entry per month
//   • cumulative[]       — CUMULATIVE VALUATION row, one entry per month
//
// Used by the Projects dashboard to aggregate forecast curves across active
// projects and produce a portfolio-wide "money in next 30/60/90 days" view.
//
// This is a JS port of the portal's cffFinancials.ts extractCff function —
// kept minimal (no diff/snapshot logic, no signed-URL caching) since the
// dashboard only needs the latest forecast.
//
// SheetJS is loaded lazily from CDN on first call (same pattern as
// paExtractor.js and HSHandover.jsx) so the bundle stays small for users
// who never visit the Projects page.
// ─────────────────────────────────────────────────────────────────────────────

const PRIMARY_FOLDER = '00-project-information'
const CFF_SUBFOLDER = 'cff'

// Lazily load SheetJS UMD build. Returns the global once attached.
async function loadXlsx() {
  if (typeof window === 'undefined') throw new Error('xlsx is browser-only')
  if (window.XLSX) return window.XLSX
  return await new Promise((resolve, reject) => {
    const s = document.createElement('script')
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js'
    s.onload = () => {
      if (window.XLSX) resolve(window.XLSX)
      else reject(new Error('XLSX failed to attach to window'))
    }
    s.onerror = () => reject(new Error('Failed to load SheetJS'))
    document.head.appendChild(s)
  })
}

// Locate the column-header row by scanning for "ref"+"description"+"total"
// markers within the first 20 rows. Matches CFFs generated by cffGenerator.js.
function findHeaderRow(rows) {
  for (let r = 0; r < Math.min(rows.length, 20); r++) {
    const joined = (rows[r] || []).map(c => String(c || '').toLowerCase()).join(' ')
    if (joined.includes('ref') && joined.includes('description') && joined.includes('total')) {
      return r
    }
  }
  return -1
}

// Find a row whose first or second column matches a given label
// (case-insensitive). Used to locate "MONTHLY GROSS VALUATION" and
// "CUMULATIVE VALUATION" totals rows.
function findRowByLabel(rows, label) {
  const target = label.toUpperCase()
  for (let r = 0; r < rows.length; r++) {
    const a = rows[r]?.[0]
    const b = rows[r]?.[1]
    if (typeof a === 'string' && a.trim().toUpperCase() === target) return r
    if (typeof b === 'string' && b.trim().toUpperCase() === target) return r
  }
  return -1
}

// Parse the header row's month columns. CFF layout is:
//   [Ref, Description, Contract Value, Month1, Month2, ..., Total Forecast, Notes]
// We walk from col 3 onwards, stopping at "Total" or "Notes" markers.
function extractMonthLabels(headerRow) {
  const labels = []
  for (let c = 3; c < headerRow.length; c++) {
    const v = headerRow[c]
    if (v == null) continue
    const s = String(v).trim()
    if (!s) continue
    const upper = s.toUpperCase()
    if (upper.includes('TOTAL') || upper.includes('NOTES')) break
    labels.push(s)
  }
  return labels
}

// Parse a CFF xlsx ArrayBuffer. Returns:
//   { contract_sum, months[], monthly[], cumulative[] }
// Or null if the file doesn't match the expected layout.
export async function extractCff(buf) {
  try {
    const XLSX = await loadXlsx()
    const wb = XLSX.read(buf, { type: 'array' })
    const ws = wb.Sheets[wb.SheetNames[0]]
    if (!ws) return null
    const rows = XLSX.utils.sheet_to_json(ws, { header: 1, raw: true })

    const headerRowIdx = findHeaderRow(rows)
    if (headerRowIdx < 0) return null

    const months = extractMonthLabels(rows[headerRowIdx] || [])
    const numMonths = months.length
    if (numMonths === 0) return null

    const grossRowIdx = findRowByLabel(rows, 'MONTHLY GROSS VALUATION')
    const cumRowIdx = findRowByLabel(rows, 'CUMULATIVE VALUATION')
    if (grossRowIdx < 0 || cumRowIdx < 0) return null

    const grossRow = rows[grossRowIdx] || []
    const cumRow = rows[cumRowIdx] || []

    const monthly = []
    const cumulative = []
    for (let m = 0; m < numMonths; m++) {
      const grossCell = grossRow[3 + m]
      const cumCell = cumRow[3 + m]
      monthly.push(typeof grossCell === 'number' ? grossCell : 0)
      cumulative.push(typeof cumCell === 'number' ? cumCell : 0)
    }

    // contract_sum is the contract-value column total in the gross row, or
    // the last cumulative if that's missing.
    const contractSumCell = grossRow[2]
    const contractSum = typeof contractSumCell === 'number'
      ? contractSumCell
      : (cumulative[cumulative.length - 1] || 0)

    return {
      contract_sum: contractSum,
      months,
      monthly,
      cumulative,
    }
  } catch (err) {
    console.warn('[cffReader] extractCff failed:', err)
    return null
  }
}

// Find the latest CFF xlsx for a project and download its bytes.
// Walks the global cff subfolder AND any per-building cff-sub-* subfolders,
// picks the most-recently-created xlsx across all of them. (Multi-building
// projects may have separate CFFs per building — we want the project-wide
// view to use whichever was generated most recently as a representative
// curve. For per-building accuracy a fuller aggregator would sum each
// building's curve; that's a future enhancement.)
//
// Returns the ArrayBuffer or null if no CFF exists.
export async function fetchLatestCffBuffer(supabase, projectId) {
  try {
    const { data: rows, error } = await supabase
      .from('project_doc_files')
      .select('storage_path, file_name, subfolder_key, created_at')
      .eq('project_id', projectId)
      .eq('folder_key', PRIMARY_FOLDER)
      .like('subfolder_key', `${CFF_SUBFOLDER}%`)   // matches 'cff', 'cff-sub-...', 'cff-archive'
      .order('created_at', { ascending: false })
    if (error) throw error
    if (!rows || rows.length === 0) return null

    // Filter to xlsx, exclude archive subfolder (those are old versions).
    const xlsxRows = rows.filter(r =>
      /\.xlsx$/i.test(r.file_name) && r.subfolder_key !== 'cff-archive'
    )
    if (xlsxRows.length === 0) return null

    // Take the most recent. (No PA-style sort needed — CFF filenames follow
    // a different convention; created_at is the right ordering for
    // "the user's most recent generation".)
    const latest = xlsxRows[0]
    const { data: signed } = await supabase
      .storage.from('project-docs')
      .createSignedUrl(latest.storage_path, 600)
    if (!signed?.signedUrl) return null

    const res = await fetch(signed.signedUrl)
    if (!res.ok) return null
    return await res.arrayBuffer()
  } catch (err) {
    console.warn('[cffReader] fetchLatestCffBuffer failed:', err)
    return null
  }
}

// Convenience: fetch + parse the latest CFF in one go.
// Returns null if no CFF or if parse fails.
export async function fetchLatestCff(supabase, projectId) {
  const buf = await fetchLatestCffBuffer(supabase, projectId)
  if (!buf) return null
  return await extractCff(buf)
}

// Given a CFF extract and a project start_date, project the monthly cashflow
// onto absolute calendar months. The CFF's months[0] is assumed to align
// with the project's start_date month.
//
// Returns an array of { date: 'YYYY-MM-01', amount: number } — one entry per
// month from start through start + months.length.
export function projectCffOnCalendar(cffExtract, projectStartDate) {
  if (!cffExtract || !projectStartDate) return []
  const start = new Date(projectStartDate)
  if (isNaN(start.getTime())) return []
  // Normalise to first of the month — we project monthly buckets, not days.
  start.setDate(1)
  const out = []
  for (let i = 0; i < cffExtract.monthly.length; i++) {
    const d = new Date(start.getFullYear(), start.getMonth() + i, 1)
    const ymd = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-01`
    out.push({ date: ymd, amount: cffExtract.monthly[i] || 0 })
  }
  return out
}
